Created test code in Main
Encountering the following error:

2022-07-15 14:13:12.533 10071-10071/com.example.janecapstoneproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.janecapstoneproject, PID: 10071
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.janecapstoneproject/com.example.janecapstoneproject.MainActivity}: java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
        at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:77)
        at de.sfuhrm.radiobrowser4j.RadioBrowser.newClient(RadioBrowser.java:130)
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:115)
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:82)
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:160)
        at com.example.janecapstoneproject.MainActivity.initRadioBrowser(MainActivity.java:133)
        at com.example.janecapstoneproject.MainActivity.onCreate(MainActivity.java:81)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
        at jakarta.ws.rs.client.FactoryFinder.find(FactoryFinder.java:168)
        at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:62)
        at de.sfuhrm.radiobrowser4j.RadioBrowser.newClient(RadioBrowser.java:130) 
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:115) 
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:82) 
        at de.sfuhrm.radiobrowser4j.RadioBrowser.<init>(RadioBrowser.java:160) 
        at com.example.janecapstoneproject.MainActivity.initRadioBrowser(MainActivity.java:133) 
        at com.example.janecapstoneproject.MainActivity.onCreate(MainActivity.java:81) 
        at android.app.Activity.performCreate(Activity.java:8207) 
        at android.app.Activity.performCreate(Activity.java:8191) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)